mainmatter/sheepdog

src/lib/handlers/default.ts, src/lib/handlers/enqueue.ts, src/lib/handlers/types.ts, src/lib/task.ts, src/routes/+page.svelte
Making this pr so that we can evaluate if we like this abstraction to create handlers...i've implemented the default one and enqueue. 
I'm open to name critiques and also general discussion on the approach. Basically we just have an object with all the handlers and every handler is a factory handler (so that it can have internal state like the queue or stuff like that).
For the moment i've passed the promise and the abort controller to the actual runner so that inside it it can await the promise to make sure the task instance finished running or stop it (we will need it for the restartable)
EDIT: i've also added the automatic creation of a series of shorthands. Basically whenever you add a new handler you will be able to create that handler like this
```ts
task(async ()=>{},{kind: …
```
=> feat: handlers abstraction + queue

.github/workflows/publish.yml, .prettierrc, RELEASE.md, package.json, renovate.json
This PR updates the renovate config to group all non-major package upgrades and creates a PR for them once per week, major versions should be separated out into their own PR and all versions should be pinned.
This PR also fixes linting issues that were left over from other commits
=> Update renovate config

src/lib/handlers/restart.ts, src/lib/task.ts, src/routes/+page.svelte, src/routes/Child.svelte
This is currently WIP, I'm having trouble cancelling the current task instance. The `abort_controller` seems to have two difference instances, the one in the task and the one in the handler, aborting the one in the task doesn't abort the one in the handler, meaning that the promise still resolves even if the controller has been aborted
=> Add `restart` task

src/lib/handlers/drop.ts, src/lib/task.ts, src/routes/+page.svelte
This PR adds the `drop` task. Building on the incredible work done in #10, this PR adds the ability to ignore subsequent attempts to start a task while another instance of the task is already running
=> Add `drop` task

.github/workflows/plan-release.yml
This should fix the linting problem we have with `release-plan`, at least temporarily.
=> chore: format after prepare release

src/lib/handlers/drop.ts
We should probably abort the controller when we drop a task to give the user a way of checking if the task instance was cancelled
=> fix: abort when dropping

src/lib/task.ts, src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js, src/lib/tests/expected-transforms/add-yield-after-await/transform.js, src/lib/tests/expected-transforms/add-yield-after-multiple-await/transform.js, src/lib/tests/expected-transforms/task-aliased-plus-task-from-another-library/transform.js, src/lib/tests/expected-transforms/task-aliased-plus-task-function/transform.js, src/lib/tests/expected-transforms/task-aliased/transform.js, src/lib/vite.ts
So after today discussion i couldn't bother not trying this.
I've passed back the value from the awaited next if the function is a generator allowing for a syntax like this
```ts
task(async function*(){
const value = yield fetch("something");
});
```
this still sucks in TS so we should still recommend users to do this
```ts
task(async function*(){
const value = await fetch("something");
yield;
});
```
BUT
this allow us to change the async transform to transform this
```ts
task(async() => {
const value = await fetch("something");
});
```
into this
```ts
task(async function*(){
const value = yield fetch("something");
});
```
the advantage of this is that if the task is aborted while the promise still hasn't resolved after it resolve we don't assign to value which could be much better if …
=> feat: better async transform (yield replace await)

.github/workflows/lint.yml, .github/workflows/plan-release.yml, .github/workflows/publish.yml, .github/workflows/test.yml
We should use latest pnpm in workflows (`release-plan` is also failing because of this)
=> chore: use pnpm 9 in workflows

src/lib/index.ts, src/lib/tests/components/default.svelte, src/lib/tests/components/drop.svelte, src/lib/tests/components/enqueue.svelte, src/lib/tests/components/link/child.svelte, src/lib/tests/components/link/parent.svelte, src/lib/tests/components/restart.svelte, src/lib/tests/components/wrong-kind.svelte, src/lib/tests/task.test.ts, vite.config.ts
Closes #70 
Added the last bit of coverage needed...it's not needed but it does feel cool
=> chore: test for errors thrown in perform

src/lib/handlers/keep_latest.ts, src/lib/task.ts, src/lib/tests/components/keep_latest.svelte, src/lib/tests/task.test.ts, src/routes/+page.svelte
This PR adds the `keep_latest` task type. 
Copying from ember-concurrency, `keep_latest` will create a queue of subsequent tasks but only run the most recent addition when the current instance has completed
=> Add keep_latest

src/lib/task.ts, src/lib/tests/components/default.svelte, src/lib/tests/components/drop.svelte, src/lib/tests/components/enqueue.svelte, src/lib/tests/components/keep_latest.svelte, src/lib/tests/components/restart.svelte, src/lib/tests/task.test.ts
Closes #87 
This also kinda setup the testing for the derived state (which i think we should test separately for each field and following this pattern of adding the expected values in the each)...let me know what you think about it.
=> feat: add performCount to derived state

src/lib/core.ts, src/lib/task.ts, vite.config.ts
A bit of spare time today...i moved all the logic for task into `createTask` inside a `core.ts` file and used an adapter pattern to communicate between the logic and the layer that build the integration with svelte stores.
This will make it much easier to switch to runes or go agnostic if we decide too.
I've used camelCase for this since we might endup exposing this function.
One thing that i don't properly like about this approach is that each adapter will need to add the handlers in it's module, i've tried abstracting that away but i got owned by TS.
I've also renamed the derived states to camelCase so if we merge this before the docs we can more easily work on adding the other derived states (which btw i think will need a bit of rework since the general loading state should be derived …
=> feat: abstract task logic to core

src/lib/index.ts, src/lib/task.ts, src/lib/tests/task.test.ts
WIP: still need to add tests and docs
This PR moves the task specific details into the `TaskInstance` interface and uses that to update the `Task` derived state
Closes #82
Closes #85 
Closes #86 
Closes #83
=> Add TaskInstance and derive `last`

src/lib/core.ts, src/lib/handlers/restart.ts, src/lib/index.ts, src/lib/task.ts, src/lib/tests/components/default.svelte, src/lib/tests/components/drop.svelte, src/lib/tests/components/enqueue.svelte, src/lib/tests/components/keep_latest.svelte, src/lib/tests/components/link/child.svelte, src/lib/tests/components/link/parent.svelte, src/lib/tests/components/restart.svelte, src/lib/tests/task.test.ts
Closes #93 and probably #94 too
Pretty nasty bug: when cancelled we need to resolve the promise in some way or it will hang indefinitely. This was shown in task types that were waiting for the old one to finish but it was a general bug.
For the moment i've opted into rejecting the promise with a Custom Error so that the user can check against that instance if the task has been cancelled. This feels the right thing to do but i would love your opinion on this when you are back from vacation @beerinho @nickschot 
I also realized that we were doing something wrong with the restart so i moved the array to be a set and removed that specific instance instead of popping the array.
=> fix: cancelled instances hanging indefinitely

README.md, src/lib/index.ts, src/lib/task.ts
This PR was initially just meant to remove the `results` array from the task store, but then I realised that `TaskDerivedState` should probably be called `TaskInstance` and that led me to also update the README
Closes #102
=> Remove `results` array

README.md, src/lib/index.ts, src/lib/tests/task.test.ts, src/lib/tests/utils.test.ts, src/lib/utils.ts, src/routes/+page.svelte, src/routes/Child.svelte
This PR adds the `timeout` utility function. It also updates all the tests, example code and examples to use it.
Closes #111
=> Add timeout utility function

package.json
This PR adds two things to make development easier:
- it pins node and pnpm to the latest versions,
- it adds `docs:dev` and `docs:install` commands to the root repo so that we don't need to change folders to run the docs site
=> Quality-of-life additions

package.json, src/lib/tests/expected-transforms/dot-notation/code.js, src/lib/tests/expected-transforms/dot-notation/transform.js, src/lib/tests/expected-transforms/generate-expected.ts, src/lib/tests/expected-transforms/with-options/code.js, src/lib/tests/expected-transforms/with-options/transform.js, src/lib/tests/task.test.ts, src/lib/tests/utils.test.ts, src/lib/vite.ts, src/vitest-setup.ts
Closes #136 
I also made some change to the expected generated script to avoid overriding old values unless you pass -f as an argument. This is because technically the rest should still be working as before unless we make a breaking change and in that case we can force.
=> fix: make async transform with dot notation too

src/lib/core.ts, src/lib/internal/helpers.ts, src/lib/task.ts, vite.config.ts
Closes #131 
This modify the adapter to add both a `onInstanceCreate` and `returnModifier` that allow every user of `core` (basically us when we will build more versions of the library) to modify the return value of `perform`.
In this case we are also attaching a subscribe function so that the whole thing is a store that contains the derived state. When we will switch to runes we will probably create a state out it before returning it.
I've also added a `retry: 1` to the vite config because we saw some flaky tests (probably related to some milliseconds changes)
@nickschot since me and @beerinho paired on this it would be good to have your review on this.
=> feat: return derived state to `perform` return value

src/lib/task.ts, src/lib/tests/components/enqueue.svelte, src/lib/tests/task.test.ts
~Blocked by #132~
The PR adds two new properties to the TaskInstance:
- `hasStarted` - starts as `false` and then as soon as the instance is started it changes to `true`,
- `isFinished` - starts as `false` and regardless of how it finishes (errored, cancelled or successfully) will switch to `true`
Closes #125
Closes #127
=> Extend the TaskInstance derived state

src/lib/core.ts, src/lib/tests/components/default.svelte, src/lib/tests/components/drop.svelte, src/lib/tests/components/enqueue.svelte, src/lib/tests/components/keep_latest.svelte, src/lib/tests/components/restart.svelte, src/lib/tests/task.test.ts
Closes #135 
I've also updated your tests @beerinho because it was still better to do it this way 😄
=> fix: avoid changing state of successful task to cancelled

apps/docs/package.json, apps/docs/src/content/docs/Example.svelte, apps/docs/src/content/docs/Timeline.svelte, apps/docs/src/content/docs/TimelineItem.svelte, apps/docs/src/content/docs/index.mdx, apps/docs/src/styles/global.css, package.json, packages/svelte/package.json, pnpm-lock.yaml
Closes #140 
~I couldn't figure out the best way to do the imports so please let me know if there is a better way.~ fixed by moving to a monorepo
You can see it locally by running `pnpm docs:dev`
=> Add timeline for docs site

apps/docs/src/components/Tabs.svelte, apps/docs/src/content/docs/Example.svelte
This PR adds the Tabs component which is simply a styling wrapper that can wrap a number of buttons and it will add the styles to turn them into a line of "tabs" the only important distinction is that the active button needs to have the "active" class set
Closes #161
=> Add Tabs component

apps/docs/astro.config.mjs, apps/docs/src/content/docs/getting-started/usage.mdx, apps/docs/src/content/docs/reference/task-instance.mdx
This PR moves the TaskInstance docs to "reference" and refers to its new home in the "Basic Usage" section
Closes #174
=> Move Task Instance to reference

apps/docs/astro.config.mjs, apps/docs/src/content/docs/explainers/linking-tasks.mdx, apps/docs/src/content/docs/reference/default.mdx, apps/docs/src/content/docs/reference/drop.mdx, apps/docs/src/content/docs/reference/enqueue.mdx, apps/docs/src/content/docs/reference/keep-latest.mdx, apps/docs/src/content/docs/reference/restart.mdx, apps/docs/src/content/docs/reference/sheepdog-utils.mdx
This PR adds an explainer for linked tasks, and a reference for SheepdogUtils (it was also incorrectly named "SheepdogOptions" in the docs so that has been finished now)
Closes #175 
Closes #176
=> Add SheepdogUtils & Linked task docs

packages/svelte/README.md, packages/svelte/src/routes/+page.svelte
After the confusion about the asyncTransform as witnessed by @paoloricciuti, I decided to add a little note reminding us of the issue when running the app locally. 
This also updates the README to show the correct import path
=> Add asyncTransform note

package.json
Turns out that netlify has been using pnpm@8 to install stuff 🫠 
> Installing npm packages using pnpm version 8.15.8
This adds a packageManager line to the pakcage.json for netlify (and people using corepack) to use the right pnpm 👍
=> add corepack to fix netlify

packages/svelte/src/lib/tests/expected-transforms/add-yield-after-await-assignment/code.js, packages/svelte/src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js, packages/svelte/src/lib/tests/expected-transforms/statements-in-blocks/transform.js, packages/svelte/src/lib/vite.ts
During lunch i had an epiphany...we were doing a lot of manual work in the async transform but it was way simpler to delegate that work to `zimmerframe`...i also removed the async search of the name which (strangely for async code /s) was adding complexity while we could just search sync (we need to walk twice but the overhead is minimal).
=> fix: way better async transform

packages/svelte/package.json
Add the `utils` export so that even if we don't get the treeshake from the main export people can still import from the `/task` sub export and only get that.
=> feat: add utils export

apps/docs/src/components/Hero.astro
Minor fix, broke only in production for some reason.
Before:
After:
=> Fix dark mode get started button appearing with the wrong colors

apps/docs/astro.config.mjs, apps/docs/src/components/Hero.astro
This caused some layout shift due to the logos not actually being square, but 100 x 90.
If we remove the width/height definition Astro will automatically infer the correct aspect ratio from the files.
=> Fix logo size issue

netlify.toml
This PR hopefully fixes all redirects from sheepdogjs.com to sheepdog.run based on the [netlify docs](https://docs.netlify.com/routing/redirects/redirect-options/#splats)
=> add wildcard redirects

apps/docs/src/content/docs/explainers/mid-run-cancellation.mdx
An `AbortSignal` does not need to be checked after the `fetch` using it, since `fetch` will reject on `abort`.
I initially thought that removing the check would be enough, but the following sections build on this example which makes the generator approach redundant for such a simple case. Will add further comments marking the sections.
Lowercase after colons is a more British English style. I changed it here to what apparently is more commonly seen in American English (did not know that there was this distinction beforehand). This should probably either be applied elsewhere for consistency or be reverted again.
(If this document was auto-formatted, that would probably need to be re-applied.)
=> Docs: Various fixes in "Mid run cancellation" section

packages/core/vite.ts
This issue that was brought up in #240 was merely Acorn trying to parse files that it could not parse - in this instance, it was a CSS file, but this could be the case for any type of file that is imported (image, JSON, etc.).
This PR simply wraps the `parse` call in a try-catch essentially ignore any attempts to parse non-parseable files while still outputting errors from the transform itself
Closes #240
=> Improve error handling of the async transform

.github/ISSUE_TEMPLATE/bug_report.yml
This PR adds the initial bug report template. I have purposefully left users able to create an issue without a template to give more flexibility, but if it becomes an issue we can restrict it
Part of #244
=> add bug issue template

renovate.json
Not _quite_ sure if this will do what we need, so if anyone knows.. let me know before we merge.
The intention is:
- Group all non majors as before
- Group all non majors of the `apps/docs` package in a separate PR
=> Config renovate to create separate group for docs app updates

apps/docs/src/content/docs/reference/restart.mdx, packages/core/src/index.ts, packages/svelte/package.json, packages/svelte/src/lib/tests/task.test.ts, packages/svelte/src/vitest-setup.ts
Closes #272 
I had to update a bunch of tests because using fake timers were messing with the scheduling (some microtask were never called) so i resorted to only use fake timers when we need fine grained control over it.
With this change there's a slight change in behavior but tbf i think it's the right one...if you invoke multiple perform in the same microtask the function is never invoked even for `restart` for example. So something like this
```ts
const my_task = task.restart(()=>{});
my_task.perform();
my_task.perform();
my_task.perform();
```
would actually invoke the function once, the last time while something like this
```ts
const my_task = task.restart(()=>{});
my_task.perform();
await Promise.resolve();
my_task.perform();
await Promise.resolve();
my_task.perform();
```
would …
=> fix: don't call the function if the task has been canceled before starting

packages/svelte/src/lib/task.ts, packages/vanilla/src/task.ts
As shared in the weekly this should allow for `esbuild` and `rolldown` to also properly treeshake away `task`
=> chore: allow for better treeshake in esbuild/rolldown

.prettierrc
This should fix the lint problem everytime we release
=> fix: use spaces in `package.json`'s

.github/workflows/require-label.yml
Since we need a label we might just as well enforce it so we have the feedback early instead of when we merge and `release-plan` fails.
=> chore: add require label workflow

packages/core/README.md
This is mostly to bring `@sheepdog/core` to 1.0
=> breaking: bump `@sheepdog/core` version to 1.0
