mainmatter/sheepdog

- .eslintignore
- .github/workflows/lint.yml
- .prettierignore
- package.json
This PR fixes a few minor linting issues, adds the `release-plan` files to the list of ignored files, and adds a CI workflow to lint the project on push
> Fix linting

- .github/workflows/lint.yml
This PR fixes the lint workflow by adding the `runs-on` property
> Fix lint workflow

- src/lib/handlers/restart.ts
- src/lib/tests/components/restart.svelte
- src/lib/tests/task.test.ts
- src/routes/+page.svelte
This add max to restartable, also added the tests for restartable)
> feat: add max to restartable

- .eslintignore
- .prettierignore
- README.md
- package.json
- pnpm-lock.yaml
- src/lib/tests/expected-transforms/add-yield-after-await-assignment/code.js
- src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js
- src/lib/tests/expected-transforms/add-yield-after-await/code.js
- src/lib/tests/expected-transforms/add-yield-after-await/transform.js
- src/lib/tests/expected-transforms/add-yield-after-multiple-await/code.js
- src/lib/tests/expected-transforms/add-yield-after-multiple-await/transform.js
- src/lib/tests/expected-transforms/async-to-generator/code.js
- src/lib/tests/expected-transforms/async-to-generator/transform.js
- src/lib/tests/expected-transforms/generate-expected.ts
- src/lib/tests/expected-transforms/no-transform/code.js
- src/lib/tests/expected-transforms/task-aliased-plus-task-from-another-library/code.js
- src/lib/tests/expected-transforms/task-aliased-plus-task-from-another-library/transform.js
- src/lib/tests/expected-transforms/task-aliased-plus-task-function/code.js
- src/lib/tests/expected-transforms/task-aliased-plus-task-function/transform.js
- src/lib/tests/expected-transforms/task-aliased/code.js
- src/lib/tests/expected-transforms/task-aliased/transform.js
- src/lib/tests/expected-transforms/task-from-another-library/code.js
- src/lib/tests/expected-transforms/task-not-from-svelte-concurrency/code.js
- src/lib/tests/vite.test.ts
Ok i got carried away and i finished writing the tests for the transform. This should be ready to review!
> chore: async transform tests

- src/lib/task.ts
- src/lib/tests/components/link/child.svelte
- src/lib/tests/components/link/parent.svelte
- src/lib/tests/task.test.ts
- src/routes/+page.svelte
> feat: link only cancel the instance of the task that was linked

- .gitignore
- package.json
- pnpm-lock.yaml
- src/lib/tests/expected-transforms/add-yield-after-await-assignment/code.js
- src/lib/tests/expected-transforms/add-yield-after-await-assignment/transform.js
- src/lib/tests/expected-transforms/async-to-generator-no-arrow/code.js
- src/lib/tests/expected-transforms/async-to-generator-no-arrow/transform.js
- src/lib/tests/expected-transforms/statements-in-blocks/code.js
- src/lib/tests/expected-transforms/statements-in-blocks/transform.js
- src/lib/vite.ts
Turns out i was missing a bunch of cases in the async transform (namely everything inside a block). Trying to have better coverage saved us from shipping a rather incomplete async transform.
> feat: more exhaustive async transform

- src/lib/core.ts
- src/lib/task.ts
- src/lib/tests/task.test.ts
I've also renamed `isLoading` to `isRunning` technically both this commit are breaking but we are pre-1.0 so we just want a minor and i don't know how `release` works if i write breaking in the title 😄
> breaking: add instance id and derive is loading

- docs/src/content/docs/index.mdx
There was an issue with #105 that broke the starlight build, this PR fixes that issue
> Fix docs site title

- README.md
- src/lib/index.ts
- src/lib/tests/utils.test.ts
- src/lib/utils.ts
This PR adds the `didCancel` util function.
I wasn't sure where to put it so I opted for a new `utils.ts` file. Let me know if you can think of a better place for it
Closes #101
> Add didCancel util

- .github/workflows/gravity.yml
- package.json
- packages/svelte/package.json
- pnpm-lock.yaml
> Add GravityCI

- apps/docs/package.json
- packages/svelte/package.json
Fix that makes volta work as expected when calling pnpm or node commands from the subfolders.
> Add volta config to subpackages' package.json

- .github/workflows/gravity.yml
- package.json
- pnpm-lock.yaml
- build(deps): upgrade `@gravityci/cli` to `^v0.0.2`
- ci(gravity): remove unnecessary environment variable `GRAVITY_HOST`
> update gravity cli to v0.0.2

- apps/docs/src/components/Hero.astro
- apps/docs/src/components/Tabs.svelte
- apps/docs/src/components/demo.svelte
- apps/docs/src/components/landing.astro
- Integrate Sheepdog vs Native demo
- Visually integrate the demo
- Dark/light mode fixes
- Responsiveness fixes
> Landing page demo integration

- apps/docs/src/components/Footer.astro
> Add copyright to footer

- apps/docs/astro.config.mjs
- apps/docs/netlify.toml
This PR adds a redirect from sheepdogjs.com to sheepdog.run
> Add netlify redirects

- apps/docs/src/components/landing.astro
Please verify if the updated sample code makes sense! I left any list markup etc. out of the sample code as it's already quite big.
> Update example code snippets to be closer to actual demo

- .github/workflows/gravity.yml
> enable gravity again

- apps/docs/src/components/Hero.astro
- apps/docs/src/components/landing.astro
- apps/docs/src/content/docs/index.mdx
This PR updates the homepage copy
> Update homepage copy

- apps/docs/astro.config.mjs
> chore: add plausible analytics

- apps/docs/astro.config.mjs
- apps/docs/package.json
- apps/docs/src/content/docs/explainers/async-transform.mdx
- apps/docs/src/content/docs/getting-started/installation.mdx
- apps/docs/src/content/docs/reference/transform.mdx
- package.json
- packages/svelte/.gitignore
- packages/svelte/package.json
- packages/svelte/src/lib/core.ts
- packages/svelte/src/lib/index.ts
- packages/svelte/src/lib/task.ts
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform-import-from-top/code.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform-import-from-top/transform.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform-multiple-imports/code.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform-multiple-imports/transform.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform-renamed/code.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform-renamed/transform.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform/code.js
- packages/svelte/src/lib/tests/expected-transforms/wrapped-in-transform/transform.js
- packages/svelte/src/lib/tests/threeshake/index.test.ts
- packages/svelte/src/lib/tests/vite.test.ts
- packages/svelte/src/lib/utils.ts
- packages/svelte/src/lib/vite.ts
- pnpm-lock.yaml
> feat: add `transform` function to annotate a function to be transformed by the vite plugin

- .gitignore
- packages/svelte/package.json
- stderr.log
This file kept coming back as an artifact of release-plan, not sure why it wasn't in .gitignore yet but this adds it.
> Remove stderr.log & add to gitignore

- packages/core/src/index.ts
- packages/core/src/vite.ts
- packages/core/tests/vite.test.ts
First PR to generalize async transform, one will follow to not break `@sheepdog/svelte`
> feat: generalize async transform

- packages/svelte/src/lib/vite.ts
> fix: generalize async transform for `@sheepdog/svelte`

- packages/vanilla/src/index.ts
Duh...this is the issue @beerinho faced...gonna quickly self approve and publish so we can get rid of the error
> fix: utils import for vanilla

- packages/core/src/index.ts
- packages/core/src/utils.ts
- packages/svelte/src/lib/index.ts
- packages/svelte/src/lib/task.ts
Apparently we had to update all the imports 🤔
> fix: update all the imports

- packages/core/src/index.ts
> fix: better types for optional arguments

- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
- packages/core/package.json
- packages/svelte/package.json
- packages/vanilla/package.json
- pnpm-lock.yaml
Setup release plan to publish`legacy` to the `legacy` tag
> chore: setup release plan to publish to `legacy`
